import type { PresenterRemoteSlidePreview } from '@localstudio/presenter-remote/protocol';

export const joystickTrustedPresenterPreview = {
  create(label: string, backgroundColor: string): PresenterRemoteSlidePreview {
    const encodedSvg = encodeURIComponent(
      `<svg xmlns="http://www.w3.org/2000/svg" width="320" height="180"><rect width="320" height="180" fill="${backgroundColor}"/><text x="28" y="96" fill="white" font-size="28">${label}</text></svg>`,
    );
    const imageUrl = `data:image/svg+xml,${encodedSvg}`;
    return {
      backgroundColor,
      backgroundImageUrl: imageUrl,
      elements: [
        {
          assetUrl: imageUrl,
          height: 180,
          id: `${label}-image`,
          kind: 'image',
          opacity: 0.88,
          rotation: 0,
          width: 320,
          x: 96,
          y: 78,
        },
        {
          fill: '#FFFFFF',
          fontFamily: 'Inter',
          fontSize: 84,
          fontWeight: 700,
          height: 140,
          id: `${label}-title`,
          kind: 'text',
          lineHeight: 1.05,
          opacity: 1,
          rotation: 0,
          text: label,
          verticalAlign: 'middle',
          width: 900,
          x: 180,
          y: 110,
          align: 'center',
        },
        {
          fill: '#F2C94C',
          height: 120,
          id: `${label}-shape`,
          kind: 'shape',
          opacity: 0.9,
          rotation: 6,
          shape: 'rounded-rect',
          stroke: '#111827',
          strokeWidth: 4,
          width: 220,
          x: 1380,
          y: 120,
        },
        {
          assetUrl: imageUrl,
          height: 150,
          id: `${label}-gif`,
          kind: 'media',
          mediaType: 'gif',
          opacity: 1,
          rotation: 0,
          width: 220,
          x: 1320,
          y: 650,
        },
        {
          assetUrl: imageUrl,
          autoplay: false,
          height: 150,
          id: `${label}-video`,
          kind: 'media',
          loop: false,
          mediaType: 'video',
          muted: true,
          opacity: 1,
          rotation: 0,
          width: 260,
          x: 980,
          y: 640,
        },
        {
          height: 120,
          id: `${label}-missing-media`,
          kind: 'media',
          mediaType: 'video',
          opacity: 0.75,
          rotation: 0,
          width: 180,
          x: 720,
          y: 660,
        },
      ],
      height: 1080,
      width: 1920,
    };
  },
};
