export const presenterProtocolFixture = {
  createCommands() {
    return [
      { command: 'close', type: 'command' },
      { command: 'next', type: 'command' },
      { command: 'previous', type: 'command' },
      { command: 'pause-timer', type: 'command' },
      { command: 'resume-timer', type: 'command' },
      { command: 'reset-timer', type: 'command' },
      { command: 'request-state', type: 'command' },
      { command: 'start-presenting', type: 'command' },
      { command: 'go-to-page', pageId: 'page-2', type: 'command' },
      { command: 'request-previews', pageIds: ['page-1'], requestId: 'request-1', type: 'command' },
      { command: 'update-notes', notes: 'Updated', pageId: 'page-1', type: 'command' },
    ];
  },

  createPreview() {
    return {
      backgroundColor: '#101820',
      backgroundImageUrl: 'https://assets.localstudio.test/background.png',
      elements: [
        {
          align: 'center',
          fill: '#ffffff',
          fontFamily: 'Inter',
          fontSize: 32,
          fontWeight: 700,
          height: 64,
          id: 'text',
          kind: 'text',
          lineHeight: 1.2,
          opacity: 1,
          rotation: 0,
          text: 'Protocol',
          verticalAlign: 'middle',
          width: 500,
          x: 20,
          y: 30,
        },
        {
          assetUrl: 'https://assets.localstudio.test/image.png',
          height: 180,
          id: 'image',
          kind: 'image',
          opacity: 0.9,
          rotation: 0,
          width: 240,
          x: 60,
          y: 130,
        },
        {
          assetUrl: 'https://assets.localstudio.test/clip.mp4',
          autoplay: true,
          controls: false,
          height: 180,
          id: 'media',
          kind: 'media',
          loop: true,
          mediaType: 'video',
          muted: true,
          opacity: 1,
          rotation: 0,
          width: 240,
          x: 330,
          y: 130,
        },
        {
          fill: '#ffcc00',
          height: 80,
          id: 'shape',
          kind: 'shape',
          opacity: 1,
          rotation: 0,
          shape: 'rounded-rectangle',
          stroke: '#101820',
          strokeWidth: 2,
          width: 140,
          x: 20,
          y: 340,
        },
      ],
      height: 720,
      width: 1280,
    };
  },

  createState() {
    const preview = this.createPreview();

    return {
      activePageId: 'page-1',
      activePageIndex: 0,
      activePageName: 'Intro',
      builds: { current: 1, remaining: 2, total: 3 },
      buildsRemaining: 2,
      commandAvailability: ['next', 'request-previews'],
      connectedControllerCount: 1,
      deckName: 'Protocol contract',
      nextPageName: 'Close',
      nextSlidePreview: preview,
      notes: 'Speaker notes',
      pageCount: 2,
      pages: [{ id: 'page-1', name: 'Intro', preview }],
      previewMode: 'structured-fallback',
      presenterMode: 'presenting',
      shortcuts: ['Swipe to navigate'],
      slidePreview: preview,
      stream: {
        enabled: true,
        fps: 30,
        height: 720,
        peerId: 'stream-peer',
        transport: 'peerjs',
        width: 1280,
      },
      timer: { elapsedMs: 12_000, paused: false, updatedAtEpochMs: 1_786_000_000_000 },
      type: 'state',
      upcomingSlidePreviews: [{ pageId: 'page-2', pageName: 'Close', preview }],
    };
  },
} as const;
