export function createPresenterProtocolPreview() {
  return {
    backgroundColor: '#101820',
    backgroundImageUrl: 'https://assets.localstudio.test/background.png',
    elements: [
      {
        align: 'center',
        fill: '#ffffff',
        fontFamily: 'Inter',
        fontSize: 32,
        fontWeight: 700,
        height: 64,
        id: 'text',
        kind: 'text',
        lineHeight: 1.2,
        opacity: 1,
        rotation: 0,
        text: 'Protocol',
        verticalAlign: 'middle',
        width: 500,
        x: 20,
        y: 30,
      },
      {
        assetUrl: 'https://assets.localstudio.test/image.png',
        height: 180,
        id: 'image',
        kind: 'image',
        opacity: 0.9,
        rotation: 0,
        width: 240,
        x: 60,
        y: 130,
      },
      {
        assetUrl: 'https://assets.localstudio.test/clip.mp4',
        autoplay: true,
        controls: false,
        height: 180,
        id: 'media',
        kind: 'media',
        loop: true,
        mediaType: 'video',
        muted: true,
        opacity: 1,
        rotation: 0,
        width: 240,
        x: 330,
        y: 130,
      },
      {
        fill: '#ffcc00',
        height: 80,
        id: 'shape',
        kind: 'shape',
        opacity: 1,
        rotation: 0,
        shape: 'rounded-rectangle',
        stroke: '#101820',
        strokeWidth: 2,
        width: 140,
        x: 20,
        y: 340,
      },
    ],
    height: 720,
    width: 1280,
  };
}
