export const editorAiWorkflowTourSelectors = {
  aiFeatureSetup: 'ai-feature-setup',
  aiToolsPanel: 'ai-tools-panel',
  aiToolsTab: 'left-tool-tab-ai-tools',
  fileImportMenuItem: 'file-import-menu-item',
  fileImportPptxItem: 'file-import-pptx-item',
  fileMenuButton: 'file-menu-button',
  footerSettings: 'footer-settings',
  giphyConfig: 'giphy-config',
  mediaIntegrationsActions: 'media-integrations-actions',
  mediaIntegrationsPanel: 'media-integrations-panel',
  mirrorSettingsActions: 'mirror-settings-actions',
  mirrorSettingsFields: 'mirror-settings-fields',
  promptCreateImageToken: 'prompt-create-image-token',
  promptExamples: 'prompt-examples',
  promptSubmitActions: 'prompt-submit-actions',
  promptWorkflow: 'prompt-workflow',
  settingsMediaRow: 'settings-media-row',
  settingsPanel: 'settings-panel',
  storageToggle: 'storage-toggle',
  unsplashConfig: 'unsplash-config',
};
