const GEMMA_LLM_MODEL_ID = 'gemma-4-webgpu-llm';
const GEMMA_LLM_TRANSFORMERS_MODEL_ID = 'onnx-community/gemma-4-E2B-it-ONNX';
const GEMMA_LLM_DISPLAY_NAME = 'Gemma 4 E2B';
const GEMMA_LLM_READY_KEY = 'localstudio.ai.model.gemma-4-webgpu-llm.ready';

const TRANSLATEGEMMA_MODEL_ID = 'translategemma-webgpu';
const TRANSLATEGEMMA_TRANSFORMERS_MODEL_ID = 'onnx-community/translategemma-text-4b-it-ONNX';
const TRANSLATEGEMMA_DISPLAY_NAME = 'TranslateGemma 4B';
const TRANSLATEGEMMA_READY_KEY = 'localstudio.ai.model.translategemma-webgpu.ready';

const LANGUAGE_DETECTION_MODEL_ID = 'language-detection-webgpu';
const LANGUAGE_DETECTION_TRANSFORMERS_MODEL_ID = 'onnx-community/xlm-roberta-base-language-detection-ONNX';
const LANGUAGE_DETECTION_DISPLAY_NAME = 'XLM-RoBERTa Base 270M';
const LANGUAGE_DETECTION_READY_KEY = 'localstudio.ai.model.language-detection-webgpu.ready';

const TRANSCRIPTION_LOW_LATENCY_MODEL_ID = 'transcription-low-latency-en';
const TRANSCRIPTION_LOW_LATENCY_TRANSFORMERS_MODEL_ID = 'onnx-community/whisper-tiny.en';
const TRANSCRIPTION_LOW_LATENCY_DISPLAY_NAME = 'Whisper Tiny EN';
const TRANSCRIPTION_LOW_LATENCY_READY_KEY = 'localstudio.ai.model.transcription-low-latency-en.ready';

const TRANSCRIPTION_BALANCED_MODEL_ID = 'transcription-balanced-en';
const TRANSCRIPTION_BALANCED_TRANSFORMERS_MODEL_ID = 'onnx-community/whisper-base';
const TRANSCRIPTION_BALANCED_DISPLAY_NAME = 'Whisper Base EN';
const TRANSCRIPTION_BALANCED_READY_KEY = 'localstudio.ai.model.transcription-balanced-en.ready';

const TRANSCRIPTION_EXPERIMENTAL_MODEL_ID = 'transcription-experimental-live';
const TRANSCRIPTION_EXPERIMENTAL_TRANSFORMERS_MODEL_ID = 'onnx-community/moonshine-base-ONNX';
const TRANSCRIPTION_EXPERIMENTAL_DISPLAY_NAME = 'Moonshine Base ASR';
const TRANSCRIPTION_EXPERIMENTAL_READY_KEY =
  'localstudio.ai.model.transcription-experimental-live.ready';

const TRANSCRIPT_EMBEDDINGS_MODEL_ID = 'transcript-embeddings-minilm';
const TRANSCRIPT_EMBEDDINGS_TRANSFORMERS_MODEL_ID = 'onnx-community/all-MiniLM-L6-v2-ONNX';
const TRANSCRIPT_EMBEDDINGS_DISPLAY_NAME = 'MiniLM Transcript Embeddings';
const TRANSCRIPT_EMBEDDINGS_READY_KEY = 'localstudio.ai.model.transcript-embeddings-minilm.ready';

const TRANSCRIPT_EMBEDDINGS_FAST_MODEL_ID = 'transcript-embeddings-mxbai';
const TRANSCRIPT_EMBEDDINGS_FAST_TRANSFORMERS_MODEL_ID = 'mixedbread-ai/mxbai-embed-xsmall-v1';
const TRANSCRIPT_EMBEDDINGS_FAST_DISPLAY_NAME = 'mxbai Fast Transcript Embeddings';
const TRANSCRIPT_EMBEDDINGS_FAST_READY_KEY =
  'localstudio.ai.model.transcript-embeddings-mxbai.ready';

const TRANSCRIPT_QA_MODEL_ID = 'transcript-qa-gemma-270m';
const TRANSCRIPT_QA_TRANSFORMERS_MODEL_ID = 'onnx-community/gemma-3-270m-ONNX';
const TRANSCRIPT_QA_DISPLAY_NAME = 'Gemma 3 270M Transcript Q&A';
const TRANSCRIPT_QA_READY_KEY = 'localstudio.ai.model.transcript-qa-gemma-270m.ready';

export const aiModelCatalog = {
  GEMMA_LLM_MODEL_ID,
  GEMMA_LLM_TRANSFORMERS_MODEL_ID,
  GEMMA_LLM_DISPLAY_NAME,
  GEMMA_LLM_READY_KEY,
  TRANSLATEGEMMA_MODEL_ID,
  TRANSLATEGEMMA_TRANSFORMERS_MODEL_ID,
  TRANSLATEGEMMA_DISPLAY_NAME,
  TRANSLATEGEMMA_READY_KEY,
  LANGUAGE_DETECTION_MODEL_ID,
  LANGUAGE_DETECTION_TRANSFORMERS_MODEL_ID,
  LANGUAGE_DETECTION_DISPLAY_NAME,
  LANGUAGE_DETECTION_READY_KEY,
  TRANSCRIPTION_LOW_LATENCY_MODEL_ID,
  TRANSCRIPTION_LOW_LATENCY_TRANSFORMERS_MODEL_ID,
  TRANSCRIPTION_LOW_LATENCY_DISPLAY_NAME,
  TRANSCRIPTION_LOW_LATENCY_READY_KEY,
  TRANSCRIPTION_BALANCED_MODEL_ID,
  TRANSCRIPTION_BALANCED_TRANSFORMERS_MODEL_ID,
  TRANSCRIPTION_BALANCED_DISPLAY_NAME,
  TRANSCRIPTION_BALANCED_READY_KEY,
  TRANSCRIPTION_EXPERIMENTAL_MODEL_ID,
  TRANSCRIPTION_EXPERIMENTAL_TRANSFORMERS_MODEL_ID,
  TRANSCRIPTION_EXPERIMENTAL_DISPLAY_NAME,
  TRANSCRIPTION_EXPERIMENTAL_READY_KEY,
  TRANSCRIPT_EMBEDDINGS_MODEL_ID,
  TRANSCRIPT_EMBEDDINGS_TRANSFORMERS_MODEL_ID,
  TRANSCRIPT_EMBEDDINGS_DISPLAY_NAME,
  TRANSCRIPT_EMBEDDINGS_READY_KEY,
  TRANSCRIPT_EMBEDDINGS_FAST_MODEL_ID,
  TRANSCRIPT_EMBEDDINGS_FAST_TRANSFORMERS_MODEL_ID,
  TRANSCRIPT_EMBEDDINGS_FAST_DISPLAY_NAME,
  TRANSCRIPT_EMBEDDINGS_FAST_READY_KEY,
  TRANSCRIPT_QA_MODEL_ID,
  TRANSCRIPT_QA_TRANSFORMERS_MODEL_ID,
  TRANSCRIPT_QA_DISPLAY_NAME,
  TRANSCRIPT_QA_READY_KEY,
};
