export function createCommandContractProject() {
  return {
    assets: {
      'asset-image': {
        id: 'asset-image',
        mimeType: 'image/png',
        name: 'Image',
        objectUrl: 'data:image/png;base64,AA==',
        type: 'image',
      },
      'asset-video': {
        id: 'asset-video',
        mimeType: 'video/mp4',
        name: 'Video',
        objectUrl: 'data:video/mp4;base64,AA==',
        type: 'video',
      },
    },
    createdAt: '2026-01-01T00:00:00.000Z',
    elements: {
      'text-1': {
        align: 'left',
        fill: '#111111',
        fontFamily: 'Inter',
        fontSize: 40,
        fontWeight: 400,
        height: 120,
        id: 'text-1',
        lineHeight: 1.1,
        locked: false,
        opacity: 1,
        rotation: 0,
        text: 'Original',
        type: 'text',
        visible: true,
        width: 500,
        x: 10,
        y: 20,
      },
      'shape-1': {
        fill: '#eeeeee',
        height: 120,
        id: 'shape-1',
        locked: false,
        opacity: 1,
        rotation: 0,
        shape: 'rectangle',
        stroke: '#222222',
        strokeWidth: 2,
        type: 'shape',
        visible: true,
        width: 300,
        x: 80,
        y: 160,
      },
      'image-1': {
        assetId: 'asset-image',
        height: 240,
        id: 'image-1',
        locked: false,
        opacity: 1,
        rotation: 0,
        type: 'image',
        visible: true,
        width: 320,
        x: 180,
        y: 260,
      },
      'video-1': {
        assetId: 'asset-video',
        autoplayInPreview: false,
        controls: true,
        height: 260,
        id: 'video-1',
        locked: false,
        loop: false,
        muted: true,
        opacity: 1,
        repeatMode: 'none',
        rotation: 0,
        startOnClick: true,
        trimStartSeconds: 0,
        type: 'video',
        visible: true,
        volume: 0.7,
        width: 420,
        x: 260,
        y: 300,
      },
    },
    fonts: {},
    id: 'project-1',
    name: 'Command Contract',
    pages: [
      {
        background: { color: '#ffffff', type: 'color' },
        elementIds: ['text-1', 'shape-1', 'image-1', 'video-1'],
        height: 1080,
        id: 'page-1',
        name: 'Slide 1',
        visible: true,
        width: 1920,
      },
    ],
    themeGallery: [],
    themes: {},
    updatedAt: '2026-01-01T00:00:00.000Z',
  };
}
