export const localStudioAnalyticsConfig = {
  googleAnalytics: {
    measurementId: 'G-FDGKZ1Q1XC',
  },
  postHog: {
    apiHost: 'https://us.i.posthog.com',
    apiKey: 'phc_m3Xa7Eu3ab39T46WUodeyn7HENWM8YYechHAo9Wk43t5',
    events: {
      aiImageGenerated: 'ai_image_generated',
      aiSlideGenerated: 'ai_slide_generated',
      backgroundRemoved: 'background_removed',
      deckTranslated: 'deck_translated',
      fontDownloaded: 'font_downloaded',
      localFontImported: 'local_font_imported',
      localMediaImported: 'local_media_imported',
      modelDownloaded: 'model_downloaded',
      presentationExportedImages: 'presentation_exported_images',
      presentationExportedPptx: 'presentation_exported_pptx',
      presentationImportedPptx: 'presentation_imported_pptx',
      presentationShared: 'presentation_shared',
      presentationStartedFullscreen: 'presentation_started_fullscreen',
      presenterRemoteOpened: 'presenter_remote_opened',
      presenterViewOpened: 'presenter_view_opened',
      projectImportedLocal: 'project_imported_local',
      projectRestoredVersion: 'project_restored_version',
      projectSavedLocal: 'project_saved_local',
      projectSyncedRemoteMirror: 'project_synced_remote_mirror',
      promptGeneratedImage: 'prompt_generated_image',
      promptGeneratedSlide: 'prompt_generated_slide',
      remoteMirrorImported: 'remote_mirror_imported',
      shareLinkCopied: 'share_link_copied',
      stockMediaInserted: 'stock_media_inserted',
    },
  },
} as const;
