export const featureMediaImages = {
  pptx: {
    src: '/bring-your-own-ppt-showcase.png',
    srcSet: '/bring-your-own-ppt-showcase-645.webp 645w',
    alt: 'LocalStudio editor importing a PowerPoint presentation with the File menu open',
    aspectRatio: '4104 / 2390',
    width: 4104,
    height: 2390,
  },
  prompt: {
    src: '/prompt-to-slide-showcase.png',
    srcSet: '/prompt-to-slide-showcase-645.webp 645w',
    alt: 'LocalStudio prompt-to-slide editor with an AI Design Revolution slide',
    aspectRatio: '2982 / 2390',
    width: 2982,
    height: 2390,
  },
  image: {
    src: '/prompt-to-image-showcase.png',
    srcSet: '/prompt-to-image-showcase-645.webp 645w',
    alt: 'LocalStudio prompt-to-image editor with a generated AI chip image on a slide',
    aspectRatio: '2970 / 2398',
    width: 2970,
    height: 2398,
  },
  translate: {
    src: '/translate-showcase-editor.png',
    srcSet: '/translate-showcase-editor-645.webp 645w',
    alt: 'LocalStudio translate menu selecting Portuguese as the target language',
    aspectRatio: '4112 / 2332',
    width: 4112,
    height: 2332,
  },
  presenter: {
    src: '/present-with-confidence-showcase.png',
    srcSet: '/present-with-confidence-showcase-645.webp 645w',
    alt: 'LocalStudio presenter mode with speaker notes and phone remote controls',
    aspectRatio: '4112 / 2312',
    width: 4112,
    height: 2312,
  },
  edit: {
    src: '/edit-images-showcase.png',
    srcSet: '/edit-images-showcase-645.webp 645w',
    alt: 'LocalStudio edit images workflow showing background removal segmentation on an image layer',
    aspectRatio: '2982 / 2396',
    width: 2982,
    height: 2396,
  },
  local: {
    src: '/project-history-showcase.png',
    srcSet: '/project-history-showcase-645.webp 645w',
    alt: 'LocalStudio project history panel showing saved local versions',
    aspectRatio: '4110 / 2402',
    width: 4110,
    height: 2402,
  },
  s3: {
    src: '/s3-compatible-showcase.png',
    srcSet: '/s3-compatible-showcase-645.webp 645w',
    alt: 'LocalStudio S3-compatible mirror settings beside a MinIO object browser',
    aspectRatio: '4112 / 2324',
    width: 4112,
    height: 2324,
  },
} as const;
