const IMAGE_GENERATION_MODEL_ID = 'image-generation-models';
const IMAGE_GENERATION_TRANSFORMERS_MODEL_ID = 'prism-ml/bonsai-image-ternary-4B-mlx-2bit';
const IMAGE_GENERATION_DISPLAY_NAME = 'Bonsai Image 4B';
const IMAGE_GENERATION_READY_KEY = 'ew-canvas-ai.model.image-generation-models.runtime-v1.ready';
const DEFAULT_IMAGE_GENERATION_SIZE = 512;
const DEFAULT_IMAGE_GENERATION_STEPS = 4;
const TRANSFORMERS_CACHE_KEY = 'ew-canvas-ai-transformers-cache';

export const imageGenerationModel = {
  IMAGE_GENERATION_MODEL_ID,
  IMAGE_GENERATION_TRANSFORMERS_MODEL_ID,
  IMAGE_GENERATION_DISPLAY_NAME,
  IMAGE_GENERATION_READY_KEY,
  DEFAULT_IMAGE_GENERATION_SIZE,
  DEFAULT_IMAGE_GENERATION_STEPS,
  TRANSFORMERS_CACHE_KEY,
};
